---
- name: Install Prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink my dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
      - .gemrc
      - .gitconfig
      - .gitignore
      - .inputrc
      - .tmux.conf
      - .vimrc
      - .ycm_extra_conf.py
      - .zlogin
      - .zlogout
      - .zpreztorc
      - .zshenv
      - .zshrc


- name: Clone tmux plugins
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: Install/update tmux plugins
  command: ~/.tmux/plugins/tpm/bin/update_plugins all

- name: Install/update VIM plugins
  command: vim +PlugInstall! +qall
  register: vimPluginsInstalled
